/* Auto-generated stub. All functions abort if called. */
#include <stdlib.h>
#include <stdio.h>

static void __attribute__((noreturn)) _stub_abort(const char *sym) {
    fprintf(stderr, "FATAL: stub called: %s\n", sym);
    abort();
}

void gdk_atom_intern(void) { _stub_abort("gdk_atom_intern"); }
void gdk_atom_name(void) { _stub_abort("gdk_atom_name"); }
void gdk_beep(void) { _stub_abort("gdk_beep"); }
void gdk_cairo_surface_create_from_pixbuf(void) { _stub_abort("gdk_cairo_surface_create_from_pixbuf"); }
void gdk_color_parse(void) { _stub_abort("gdk_color_parse"); }
void gdk_cursor_new_for_display(void) { _stub_abort("gdk_cursor_new_for_display"); }
void gdk_cursor_new_from_name(void) { _stub_abort("gdk_cursor_new_from_name"); }
void gdk_cursor_new_from_pixbuf(void) { _stub_abort("gdk_cursor_new_from_pixbuf"); }
void gdk_cursor_new_from_surface(void) { _stub_abort("gdk_cursor_new_from_surface"); }
void gdk_device_get_source(void) { _stub_abort("gdk_device_get_source"); }
void gdk_device_get_window_at_position(void) { _stub_abort("gdk_device_get_window_at_position"); }
void gdk_device_manager_get_client_pointer(void) { _stub_abort("gdk_device_manager_get_client_pointer"); }
void gdk_device_manager_list_devices(void) { _stub_abort("gdk_device_manager_list_devices"); }
void gdk_device_warp(void) { _stub_abort("gdk_device_warp"); }
void gdk_disable_multidevice(void) { _stub_abort("gdk_disable_multidevice"); }
void gdk_display_get_app_launch_context(void) { _stub_abort("gdk_display_get_app_launch_context"); }
void gdk_display_get_default(void) { _stub_abort("gdk_display_get_default"); }
void gdk_display_get_default_screen(void) { _stub_abort("gdk_display_get_default_screen"); }
void gdk_display_get_device_manager(void) { _stub_abort("gdk_display_get_device_manager"); }
void gdk_display_manager_get(void) { _stub_abort("gdk_display_manager_get"); }
void gdk_display_manager_open_display(void) { _stub_abort("gdk_display_manager_open_display"); }
void gdk_display_open(void) { _stub_abort("gdk_display_open"); }
void gdk_drag_context_get_actions(void) { _stub_abort("gdk_drag_context_get_actions"); }
void gdk_drag_context_get_dest_window(void) { _stub_abort("gdk_drag_context_get_dest_window"); }
void gdk_drag_context_get_device(void) { _stub_abort("gdk_drag_context_get_device"); }
void gdk_drag_context_get_selected_action(void) { _stub_abort("gdk_drag_context_get_selected_action"); }
void gdk_drag_context_get_source_window(void) { _stub_abort("gdk_drag_context_get_source_window"); }
void gdk_drag_context_list_targets(void) { _stub_abort("gdk_drag_context_list_targets"); }
void gdk_drag_status(void) { _stub_abort("gdk_drag_status"); }
void gdk_event_copy(void) { _stub_abort("gdk_event_copy"); }
void gdk_event_free(void) { _stub_abort("gdk_event_free"); }
void gdk_event_get_axis(void) { _stub_abort("gdk_event_get_axis"); }
void gdk_event_get_root_coords(void) { _stub_abort("gdk_event_get_root_coords"); }
void gdk_event_get_source_device(void) { _stub_abort("gdk_event_get_source_device"); }
void gdk_event_get_time(void) { _stub_abort("gdk_event_get_time"); }
void gdk_event_handler_set(void) { _stub_abort("gdk_event_handler_set"); }
void gdk_event_peek(void) { _stub_abort("gdk_event_peek"); }
void gdk_event_put(void) { _stub_abort("gdk_event_put"); }
void gdk_flush(void) { _stub_abort("gdk_flush"); }
void gdk_get_default_root_window(void) { _stub_abort("gdk_get_default_root_window"); }
void gdk_get_display_arg_name(void) { _stub_abort("gdk_get_display_arg_name"); }
void gdk_get_program_class(void) { _stub_abort("gdk_get_program_class"); }
void gdk_keymap_get_default(void) { _stub_abort("gdk_keymap_get_default"); }
void gdk_keymap_get_direction(void) { _stub_abort("gdk_keymap_get_direction"); }
void gdk_keymap_get_entries_for_keyval(void) { _stub_abort("gdk_keymap_get_entries_for_keyval"); }
void gdk_keymap_get_for_display(void) { _stub_abort("gdk_keymap_get_for_display"); }
void gdk_keymap_have_bidi_layouts(void) { _stub_abort("gdk_keymap_have_bidi_layouts"); }
void gdk_keymap_translate_keyboard_state(void) { _stub_abort("gdk_keymap_translate_keyboard_state"); }
void gdk_keyval_name(void) { _stub_abort("gdk_keyval_name"); }
void gdk_keyval_to_unicode(void) { _stub_abort("gdk_keyval_to_unicode"); }
void gdk_pointer_grab(void) { _stub_abort("gdk_pointer_grab"); }
void gdk_pointer_ungrab(void) { _stub_abort("gdk_pointer_ungrab"); }
void gdk_property_change(void) { _stub_abort("gdk_property_change"); }
void gdk_property_delete(void) { _stub_abort("gdk_property_delete"); }
void gdk_property_get(void) { _stub_abort("gdk_property_get"); }
void gdk_rectangle_intersect(void) { _stub_abort("gdk_rectangle_intersect"); }
void gdk_screen_get_default(void) { _stub_abort("gdk_screen_get_default"); }
void gdk_screen_get_font_options(void) { _stub_abort("gdk_screen_get_font_options"); }
void gdk_screen_get_monitor_at_window(void) { _stub_abort("gdk_screen_get_monitor_at_window"); }
void gdk_screen_get_monitor_geometry(void) { _stub_abort("gdk_screen_get_monitor_geometry"); }
void gdk_screen_get_monitor_height_mm(void) { _stub_abort("gdk_screen_get_monitor_height_mm"); }
void gdk_screen_get_monitor_scale_factor(void) { _stub_abort("gdk_screen_get_monitor_scale_factor"); }
void gdk_screen_get_monitor_workarea(void) { _stub_abort("gdk_screen_get_monitor_workarea"); }
void gdk_screen_get_n_monitors(void) { _stub_abort("gdk_screen_get_n_monitors"); }
void gdk_screen_get_resolution(void) { _stub_abort("gdk_screen_get_resolution"); }
void gdk_screen_get_rgba_visual(void) { _stub_abort("gdk_screen_get_rgba_visual"); }
void gdk_screen_get_root_window(void) { _stub_abort("gdk_screen_get_root_window"); }
void gdk_screen_get_system_visual(void) { _stub_abort("gdk_screen_get_system_visual"); }
void gdk_screen_is_composited(void) { _stub_abort("gdk_screen_is_composited"); }
void gdk_set_program_class(void) { _stub_abort("gdk_set_program_class"); }
void gdk_unicode_to_keyval(void) { _stub_abort("gdk_unicode_to_keyval"); }
void gdk_visual_get_depth(void) { _stub_abort("gdk_visual_get_depth"); }
void gdk_visual_get_system(void) { _stub_abort("gdk_visual_get_system"); }
void gdk_wayland_device_get_wl_pointer(void) { _stub_abort("gdk_wayland_device_get_wl_pointer"); }
void gdk_wayland_device_get_wl_seat(void) { _stub_abort("gdk_wayland_device_get_wl_seat"); }
void gdk_wayland_display_get_wl_compositor(void) { _stub_abort("gdk_wayland_display_get_wl_compositor"); }
void gdk_wayland_display_get_wl_display(void) { _stub_abort("gdk_wayland_display_get_wl_display"); }
void gdk_wayland_window_get_wl_surface(void) { _stub_abort("gdk_wayland_window_get_wl_surface"); }
void gdk_wayland_window_set_use_custom_surface(void) { _stub_abort("gdk_wayland_window_set_use_custom_surface"); }
void gdk_window_add_filter(void) { _stub_abort("gdk_window_add_filter"); }
void gdk_window_begin_move_drag(void) { _stub_abort("gdk_window_begin_move_drag"); }
void gdk_window_begin_resize_drag(void) { _stub_abort("gdk_window_begin_resize_drag"); }
void gdk_window_destroy(void) { _stub_abort("gdk_window_destroy"); }
void gdk_window_focus(void) { _stub_abort("gdk_window_focus"); }
void gdk_window_get_device_position(void) { _stub_abort("gdk_window_get_device_position"); }
void gdk_window_get_display(void) { _stub_abort("gdk_window_get_display"); }
void gdk_window_get_events(void) { _stub_abort("gdk_window_get_events"); }
void gdk_window_get_frame_clock(void) { _stub_abort("gdk_window_get_frame_clock"); }
void gdk_window_get_frame_extents(void) { _stub_abort("gdk_window_get_frame_extents"); }
void gdk_window_get_geometry(void) { _stub_abort("gdk_window_get_geometry"); }
void gdk_window_get_height(void) { _stub_abort("gdk_window_get_height"); }
void gdk_window_get_origin(void) { _stub_abort("gdk_window_get_origin"); }
void gdk_window_get_parent(void) { _stub_abort("gdk_window_get_parent"); }
void gdk_window_get_position(void) { _stub_abort("gdk_window_get_position"); }
void gdk_window_get_scale_factor(void) { _stub_abort("gdk_window_get_scale_factor"); }
void gdk_window_get_screen(void) { _stub_abort("gdk_window_get_screen"); }
void gdk_window_get_state(void) { _stub_abort("gdk_window_get_state"); }
void gdk_window_get_toplevel(void) { _stub_abort("gdk_window_get_toplevel"); }
void gdk_window_get_update_area(void) { _stub_abort("gdk_window_get_update_area"); }
void gdk_window_get_user_data(void) { _stub_abort("gdk_window_get_user_data"); }
void gdk_window_get_width(void) { _stub_abort("gdk_window_get_width"); }
void gdk_window_get_window_type(void) { _stub_abort("gdk_window_get_window_type"); }
void gdk_window_hide(void) { _stub_abort("gdk_window_hide"); }
void gdk_window_input_shape_combine_region(void) { _stub_abort("gdk_window_input_shape_combine_region"); }
void gdk_window_invalidate_rect(void) { _stub_abort("gdk_window_invalidate_rect"); }
void gdk_window_invalidate_region(void) { _stub_abort("gdk_window_invalidate_region"); }
void gdk_window_lower(void) { _stub_abort("gdk_window_lower"); }
void gdk_window_move(void) { _stub_abort("gdk_window_move"); }
void gdk_window_move_resize(void) { _stub_abort("gdk_window_move_resize"); }
void gdk_window_new(void) { _stub_abort("gdk_window_new"); }
void gdk_window_process_updates(void) { _stub_abort("gdk_window_process_updates"); }
void gdk_window_remove_filter(void) { _stub_abort("gdk_window_remove_filter"); }
void gdk_window_set_cursor(void) { _stub_abort("gdk_window_set_cursor"); }
void gdk_window_set_decorations(void) { _stub_abort("gdk_window_set_decorations"); }
void gdk_window_set_events(void) { _stub_abort("gdk_window_set_events"); }
void gdk_window_set_opaque_region(void) { _stub_abort("gdk_window_set_opaque_region"); }
void gdk_window_set_override_redirect(void) { _stub_abort("gdk_window_set_override_redirect"); }
void gdk_window_set_role(void) { _stub_abort("gdk_window_set_role"); }
void gdk_window_set_shadow_width(void) { _stub_abort("gdk_window_set_shadow_width"); }
void gdk_window_set_urgency_hint(void) { _stub_abort("gdk_window_set_urgency_hint"); }
void gdk_window_show(void) { _stub_abort("gdk_window_show"); }
void gdk_window_show_unraised(void) { _stub_abort("gdk_window_show_unraised"); }
void gdk_window_show_window_menu(void) { _stub_abort("gdk_window_show_window_menu"); }
void gdk_x11_atom_to_xatom(void) { _stub_abort("gdk_x11_atom_to_xatom"); }
void gdk_x11_display_get_user_time(void) { _stub_abort("gdk_x11_display_get_user_time"); }
void gdk_x11_display_get_xdisplay(void) { _stub_abort("gdk_x11_display_get_xdisplay"); }
void gdk_x11_get_default_root_xwindow(void) { _stub_abort("gdk_x11_get_default_root_xwindow"); }
void gdk_x11_get_default_xdisplay(void) { _stub_abort("gdk_x11_get_default_xdisplay"); }
void gdk_x11_get_server_time(void) { _stub_abort("gdk_x11_get_server_time"); }
void gdk_x11_get_xatom_by_name_for_display(void) { _stub_abort("gdk_x11_get_xatom_by_name_for_display"); }
void gdk_x11_lookup_xdisplay(void) { _stub_abort("gdk_x11_lookup_xdisplay"); }
void gdk_x11_screen_get_screen_number(void) { _stub_abort("gdk_x11_screen_get_screen_number"); }
void gdk_x11_screen_lookup_visual(void) { _stub_abort("gdk_x11_screen_lookup_visual"); }
void gdk_x11_screen_supports_net_wm_hint(void) { _stub_abort("gdk_x11_screen_supports_net_wm_hint"); }
void gdk_x11_set_sm_client_id(void) { _stub_abort("gdk_x11_set_sm_client_id"); }
void gdk_x11_window_get_xid(void) { _stub_abort("gdk_x11_window_get_xid"); }
void gdk_x11_window_lookup_for_display(void) { _stub_abort("gdk_x11_window_lookup_for_display"); }
void gdk_x11_xatom_to_atom(void) { _stub_abort("gdk_x11_xatom_to_atom"); }
