/* Auto-generated stub. All functions abort if called. */
#include <stdlib.h>
#include <stdio.h>

static void __attribute__((noreturn)) _stub_abort(const char *sym) {
    fprintf(stderr, "FATAL: stub called: %s\n", sym);
    abort();
}

char g_ascii_table[64] __attribute__((aligned(8)));
void g_ascii_tolower(void) { _stub_abort("g_ascii_tolower"); }
void g_ascii_toupper(void) { _stub_abort("g_ascii_toupper"); }
void g_assertion_message_expr(void) { _stub_abort("g_assertion_message_expr"); }
void g_dgettext(void) { _stub_abort("g_dgettext"); }
void g_error_free(void) { _stub_abort("g_error_free"); }
void g_error_matches(void) { _stub_abort("g_error_matches"); }
void g_filename_from_uri(void) { _stub_abort("g_filename_from_uri"); }
void g_filename_from_utf8(void) { _stub_abort("g_filename_from_utf8"); }
void g_filename_to_uri(void) { _stub_abort("g_filename_to_uri"); }
void g_file_open_tmp(void) { _stub_abort("g_file_open_tmp"); }
void g_file_test(void) { _stub_abort("g_file_test"); }
void g_find_program_in_path(void) { _stub_abort("g_find_program_in_path"); }
void g_free(void) { _stub_abort("g_free"); }
void g_getenv(void) { _stub_abort("g_getenv"); }
void g_get_host_name(void) { _stub_abort("g_get_host_name"); }
void g_get_monotonic_time(void) { _stub_abort("g_get_monotonic_time"); }
void g_get_prgname(void) { _stub_abort("g_get_prgname"); }
void g_get_user_config_dir(void) { _stub_abort("g_get_user_config_dir"); }
void g_get_user_runtime_dir(void) { _stub_abort("g_get_user_runtime_dir"); }
void g_hash_table_destroy(void) { _stub_abort("g_hash_table_destroy"); }
void g_hash_table_foreach(void) { _stub_abort("g_hash_table_foreach"); }
void g_hash_table_foreach_steal(void) { _stub_abort("g_hash_table_foreach_steal"); }
void g_hash_table_insert(void) { _stub_abort("g_hash_table_insert"); }
void g_hash_table_lookup(void) { _stub_abort("g_hash_table_lookup"); }
void g_hash_table_new_full(void) { _stub_abort("g_hash_table_new_full"); }
void g_hash_table_new(void) { _stub_abort("g_hash_table_new"); }
void g_hash_table_remove(void) { _stub_abort("g_hash_table_remove"); }
void g_hash_table_size(void) { _stub_abort("g_hash_table_size"); }
void g_idle_add(void) { _stub_abort("g_idle_add"); }
void g_int_equal(void) { _stub_abort("g_int_equal"); }
void g_intern_static_string(void) { _stub_abort("g_intern_static_string"); }
void g_int_hash(void) { _stub_abort("g_int_hash"); }
void g_io_add_watch(void) { _stub_abort("g_io_add_watch"); }
void g_io_channel_new_file(void) { _stub_abort("g_io_channel_new_file"); }
void g_io_channel_read_chars(void) { _stub_abort("g_io_channel_read_chars"); }
void g_io_channel_read_to_end(void) { _stub_abort("g_io_channel_read_to_end"); }
void g_io_channel_set_buffered(void) { _stub_abort("g_io_channel_set_buffered"); }
void g_io_channel_set_encoding(void) { _stub_abort("g_io_channel_set_encoding"); }
void g_io_channel_set_flags(void) { _stub_abort("g_io_channel_set_flags"); }
void g_io_channel_unix_get_fd(void) { _stub_abort("g_io_channel_unix_get_fd"); }
void g_io_channel_unix_new(void) { _stub_abort("g_io_channel_unix_new"); }
void g_io_channel_unref(void) { _stub_abort("g_io_channel_unref"); }
void g_io_create_watch(void) { _stub_abort("g_io_create_watch"); }
void g_key_file_free(void) { _stub_abort("g_key_file_free"); }
void g_key_file_new(void) { _stub_abort("g_key_file_new"); }
void g_key_file_to_data(void) { _stub_abort("g_key_file_to_data"); }
void glib_check_version(void) { _stub_abort("glib_check_version"); }
void g_list_append(void) { _stub_abort("g_list_append"); }
void g_list_foreach(void) { _stub_abort("g_list_foreach"); }
void g_list_free_full(void) { _stub_abort("g_list_free_full"); }
void g_list_free(void) { _stub_abort("g_list_free"); }
void g_list_length(void) { _stub_abort("g_list_length"); }
void g_list_remove(void) { _stub_abort("g_list_remove"); }
void g_list_sort(void) { _stub_abort("g_list_sort"); }
void g_log_default_handler(void) { _stub_abort("g_log_default_handler"); }
void g_log_set_default_handler(void) { _stub_abort("g_log_set_default_handler"); }
void g_log_set_handler(void) { _stub_abort("g_log_set_handler"); }
void g_logv(void) { _stub_abort("g_logv"); }
void g_main_context_default(void) { _stub_abort("g_main_context_default"); }
void g_main_context_get_poll_func(void) { _stub_abort("g_main_context_get_poll_func"); }
void g_main_context_iteration(void) { _stub_abort("g_main_context_iteration"); }
void g_main_context_set_poll_func(void) { _stub_abort("g_main_context_set_poll_func"); }
void g_main_loop_new(void) { _stub_abort("g_main_loop_new"); }
void g_main_loop_run(void) { _stub_abort("g_main_loop_run"); }
void g_main_loop_unref(void) { _stub_abort("g_main_loop_unref"); }
void g_malloc0(void) { _stub_abort("g_malloc0"); }
void g_malloc(void) { _stub_abort("g_malloc"); }
void g_malloc_n(void) { _stub_abort("g_malloc_n"); }
void g_markup_printf_escaped(void) { _stub_abort("g_markup_printf_escaped"); }
void g_once_init_enter(void) { _stub_abort("g_once_init_enter"); }
void g_once_init_leave(void) { _stub_abort("g_once_init_leave"); }
void g_path_get_basename(void) { _stub_abort("g_path_get_basename"); }
void g_path_is_absolute(void) { _stub_abort("g_path_is_absolute"); }
void g_printerr(void) { _stub_abort("g_printerr"); }
void g_private_get(void) { _stub_abort("g_private_get"); }
void g_private_set(void) { _stub_abort("g_private_set"); }
void g_ptr_array_add(void) { _stub_abort("g_ptr_array_add"); }
void g_ptr_array_sized_new(void) { _stub_abort("g_ptr_array_sized_new"); }
void g_ptr_array_unref(void) { _stub_abort("g_ptr_array_unref"); }
void g_quark_from_static_string(void) { _stub_abort("g_quark_from_static_string"); }
void g_quark_from_string(void) { _stub_abort("g_quark_from_string"); }
void g_random_int(void) { _stub_abort("g_random_int"); }
void g_random_int_range(void) { _stub_abort("g_random_int_range"); }
void g_return_if_fail_warning(void) { _stub_abort("g_return_if_fail_warning"); }
void g_set_application_name(void) { _stub_abort("g_set_application_name"); }
void g_set_error(void) { _stub_abort("g_set_error"); }
void g_set_prgname(void) { _stub_abort("g_set_prgname"); }
void g_shell_parse_argv(void) { _stub_abort("g_shell_parse_argv"); }
void g_shell_quote(void) { _stub_abort("g_shell_quote"); }
void g_slist_foreach(void) { _stub_abort("g_slist_foreach"); }
void g_slist_free(void) { _stub_abort("g_slist_free"); }
void g_slist_index(void) { _stub_abort("g_slist_index"); }
void g_slist_prepend(void) { _stub_abort("g_slist_prepend"); }
void g_source_add_poll(void) { _stub_abort("g_source_add_poll"); }
void g_source_attach(void) { _stub_abort("g_source_attach"); }
void g_source_destroy(void) { _stub_abort("g_source_destroy"); }
void g_source_new(void) { _stub_abort("g_source_new"); }
void g_source_remove(void) { _stub_abort("g_source_remove"); }
void g_source_set_callback(void) { _stub_abort("g_source_set_callback"); }
void g_source_set_can_recurse(void) { _stub_abort("g_source_set_can_recurse"); }
void g_source_set_priority(void) { _stub_abort("g_source_set_priority"); }
void g_source_unref(void) { _stub_abort("g_source_unref"); }
void g_spawn_async_with_pipes(void) { _stub_abort("g_spawn_async_with_pipes"); }
void g_spawn_sync(void) { _stub_abort("g_spawn_sync"); }
void g_strchomp(void) { _stub_abort("g_strchomp"); }
void g_strchug(void) { _stub_abort("g_strchug"); }
void g_strcmp0(void) { _stub_abort("g_strcmp0"); }
void g_strconcat(void) { _stub_abort("g_strconcat"); }
void g_strdup(void) { _stub_abort("g_strdup"); }
void g_strdup_printf(void) { _stub_abort("g_strdup_printf"); }
void g_strdupv(void) { _stub_abort("g_strdupv"); }
void g_strfreev(void) { _stub_abort("g_strfreev"); }
void g_strsplit(void) { _stub_abort("g_strsplit"); }
void g_strv_length(void) { _stub_abort("g_strv_length"); }
void g_timeout_add_full(void) { _stub_abort("g_timeout_add_full"); }
void g_timeout_add(void) { _stub_abort("g_timeout_add"); }
void g_unichar_isgraph(void) { _stub_abort("g_unichar_isgraph"); }
void g_unichar_to_utf8(void) { _stub_abort("g_unichar_to_utf8"); }
void g_unsetenv(void) { _stub_abort("g_unsetenv"); }
void g_uri_list_extract_uris(void) { _stub_abort("g_uri_list_extract_uris"); }
void g_utf8_get_char(void) { _stub_abort("g_utf8_get_char"); }
void g_utf8_offset_to_pointer(void) { _stub_abort("g_utf8_offset_to_pointer"); }
void g_utf8_strlen(void) { _stub_abort("g_utf8_strlen"); }
void g_utf8_to_utf16(void) { _stub_abort("g_utf8_to_utf16"); }
void g_variant_builder_add(void) { _stub_abort("g_variant_builder_add"); }
void g_variant_builder_add_value(void) { _stub_abort("g_variant_builder_add_value"); }
void g_variant_builder_clear(void) { _stub_abort("g_variant_builder_clear"); }
void g_variant_builder_close(void) { _stub_abort("g_variant_builder_close"); }
void g_variant_builder_end(void) { _stub_abort("g_variant_builder_end"); }
void g_variant_builder_init(void) { _stub_abort("g_variant_builder_init"); }
void g_variant_builder_open(void) { _stub_abort("g_variant_builder_open"); }
void g_variant_dup_string(void) { _stub_abort("g_variant_dup_string"); }
void g_variant_get_boolean(void) { _stub_abort("g_variant_get_boolean"); }
void g_variant_get_byte(void) { _stub_abort("g_variant_get_byte"); }
void g_variant_get_child(void) { _stub_abort("g_variant_get_child"); }
void g_variant_get_child_value(void) { _stub_abort("g_variant_get_child_value"); }
void g_variant_get_double(void) { _stub_abort("g_variant_get_double"); }
void g_variant_get_fixed_array(void) { _stub_abort("g_variant_get_fixed_array"); }
void g_variant_get(void) { _stub_abort("g_variant_get"); }
void g_variant_get_handle(void) { _stub_abort("g_variant_get_handle"); }
void g_variant_get_int32(void) { _stub_abort("g_variant_get_int32"); }
void g_variant_get_int64(void) { _stub_abort("g_variant_get_int64"); }
void g_variant_get_string(void) { _stub_abort("g_variant_get_string"); }
void g_variant_get_strv(void) { _stub_abort("g_variant_get_strv"); }
void g_variant_get_type_string(void) { _stub_abort("g_variant_get_type_string"); }
void g_variant_get_uint32(void) { _stub_abort("g_variant_get_uint32"); }
void g_variant_get_uint64(void) { _stub_abort("g_variant_get_uint64"); }
void g_variant_get_variant(void) { _stub_abort("g_variant_get_variant"); }
void g_variant_is_object_path(void) { _stub_abort("g_variant_is_object_path"); }
void g_variant_is_of_type(void) { _stub_abort("g_variant_is_of_type"); }
void g_variant_iter_free(void) { _stub_abort("g_variant_iter_free"); }
void g_variant_iter_init(void) { _stub_abort("g_variant_iter_init"); }
void g_variant_iter_loop(void) { _stub_abort("g_variant_iter_loop"); }
void g_variant_iter_new(void) { _stub_abort("g_variant_iter_new"); }
void g_variant_iter_next(void) { _stub_abort("g_variant_iter_next"); }
void g_variant_lookup(void) { _stub_abort("g_variant_lookup"); }
void g_variant_lookup_value(void) { _stub_abort("g_variant_lookup_value"); }
void g_variant_n_children(void) { _stub_abort("g_variant_n_children"); }
void g_variant_new_boolean(void) { _stub_abort("g_variant_new_boolean"); }
void g_variant_new_bytestring(void) { _stub_abort("g_variant_new_bytestring"); }
void g_variant_new_double(void) { _stub_abort("g_variant_new_double"); }
void g_variant_new_fixed_array(void) { _stub_abort("g_variant_new_fixed_array"); }
void g_variant_new_from_data(void) { _stub_abort("g_variant_new_from_data"); }
void g_variant_new(void) { _stub_abort("g_variant_new"); }
void g_variant_new_int32(void) { _stub_abort("g_variant_new_int32"); }
void g_variant_new_int64(void) { _stub_abort("g_variant_new_int64"); }
void g_variant_new_string(void) { _stub_abort("g_variant_new_string"); }
void g_variant_new_strv(void) { _stub_abort("g_variant_new_strv"); }
void g_variant_new_tuple(void) { _stub_abort("g_variant_new_tuple"); }
void g_variant_new_uint32(void) { _stub_abort("g_variant_new_uint32"); }
void g_variant_print(void) { _stub_abort("g_variant_print"); }
void g_variant_ref(void) { _stub_abort("g_variant_ref"); }
void g_variant_ref_sink(void) { _stub_abort("g_variant_ref_sink"); }
void g_variant_type_checked_(void) { _stub_abort("g_variant_type_checked_"); }
void g_variant_unref(void) { _stub_abort("g_variant_unref"); }
