/* Auto-generated stub. All functions abort if called. */
#include <stdlib.h>
#include <stdio.h>

static void __attribute__((noreturn)) _stub_abort(const char *sym) {
    fprintf(stderr, "FATAL: stub called: %s\n", sym);
    abort();
}

void gtk_accel_label_new(void) { _stub_abort("gtk_accel_label_new"); }
void gtk_accessible_get_type(void) { _stub_abort("gtk_accessible_get_type"); }
void gtk_accessible_set_widget(void) { _stub_abort("gtk_accessible_set_widget"); }
void gtk_app_chooser_dialog_get_type(void) { _stub_abort("gtk_app_chooser_dialog_get_type"); }
void gtk_app_chooser_dialog_new_for_content_type(void) { _stub_abort("gtk_app_chooser_dialog_new_for_content_type"); }
void gtk_app_chooser_dialog_set_heading(void) { _stub_abort("gtk_app_chooser_dialog_set_heading"); }
void gtk_app_chooser_get_app_info(void) { _stub_abort("gtk_app_chooser_get_app_info"); }
void gtk_app_chooser_get_type(void) { _stub_abort("gtk_app_chooser_get_type"); }
void gtk_bindings_activate(void) { _stub_abort("gtk_bindings_activate"); }
void gtk_box_get_type(void) { _stub_abort("gtk_box_get_type"); }
void gtk_box_new(void) { _stub_abort("gtk_box_new"); }
void gtk_box_pack_start(void) { _stub_abort("gtk_box_pack_start"); }
void gtk_box_set_homogeneous(void) { _stub_abort("gtk_box_set_homogeneous"); }
void gtk_button_new_with_label(void) { _stub_abort("gtk_button_new_with_label"); }
void gtk_cairo_should_draw_window(void) { _stub_abort("gtk_cairo_should_draw_window"); }
void gtk_cairo_transform_to_window(void) { _stub_abort("gtk_cairo_transform_to_window"); }
void gtk_check_button_new_with_mnemonic(void) { _stub_abort("gtk_check_button_new_with_mnemonic"); }
void gtk_check_version(void) { _stub_abort("gtk_check_version"); }
void gtk_clipboard_clear(void) { _stub_abort("gtk_clipboard_clear"); }
void gtk_clipboard_get(void) { _stub_abort("gtk_clipboard_get"); }
void gtk_clipboard_request_contents(void) { _stub_abort("gtk_clipboard_request_contents"); }
void gtk_clipboard_request_text(void) { _stub_abort("gtk_clipboard_request_text"); }
void gtk_clipboard_set_can_store(void) { _stub_abort("gtk_clipboard_set_can_store"); }
void gtk_clipboard_set_with_data(void) { _stub_abort("gtk_clipboard_set_with_data"); }
void gtk_clipboard_store(void) { _stub_abort("gtk_clipboard_store"); }
void gtk_color_chooser_dialog_new(void) { _stub_abort("gtk_color_chooser_dialog_new"); }
void gtk_color_chooser_get_rgba(void) { _stub_abort("gtk_color_chooser_get_rgba"); }
void gtk_color_chooser_get_type(void) { _stub_abort("gtk_color_chooser_get_type"); }
void gtk_color_chooser_set_rgba(void) { _stub_abort("gtk_color_chooser_set_rgba"); }
void gtk_color_chooser_set_use_alpha(void) { _stub_abort("gtk_color_chooser_set_use_alpha"); }
void gtk_combo_box_get_active(void) { _stub_abort("gtk_combo_box_get_active"); }
void gtk_combo_box_get_type(void) { _stub_abort("gtk_combo_box_get_type"); }
void gtk_combo_box_set_active(void) { _stub_abort("gtk_combo_box_set_active"); }
void gtk_combo_box_text_append(void) { _stub_abort("gtk_combo_box_text_append"); }
void gtk_combo_box_text_get_type(void) { _stub_abort("gtk_combo_box_text_get_type"); }
void gtk_combo_box_text_new(void) { _stub_abort("gtk_combo_box_text_new"); }
void gtk_container_add(void) { _stub_abort("gtk_container_add"); }
void gtk_container_check_resize(void) { _stub_abort("gtk_container_check_resize"); }
void gtk_container_forall(void) { _stub_abort("gtk_container_forall"); }
void gtk_container_get_type(void) { _stub_abort("gtk_container_get_type"); }
void gtk_container_remove(void) { _stub_abort("gtk_container_remove"); }
void gtk_container_set_border_width(void) { _stub_abort("gtk_container_set_border_width"); }
void gtk_css_provider_load_from_data(void) { _stub_abort("gtk_css_provider_load_from_data"); }
void gtk_css_provider_new(void) { _stub_abort("gtk_css_provider_new"); }
void gtk_dialog_get_content_area(void) { _stub_abort("gtk_dialog_get_content_area"); }
void gtk_dialog_get_type(void) { _stub_abort("gtk_dialog_get_type"); }
void gtk_dialog_new_with_buttons(void) { _stub_abort("gtk_dialog_new_with_buttons"); }
void gtk_dialog_run(void) { _stub_abort("gtk_dialog_run"); }
void gtk_dialog_set_default_response(void) { _stub_abort("gtk_dialog_set_default_response"); }
void gtk_drag_begin_with_coordinates(void) { _stub_abort("gtk_drag_begin_with_coordinates"); }
void gtk_drag_dest_set(void) { _stub_abort("gtk_drag_dest_set"); }
void gtk_drag_finish(void) { _stub_abort("gtk_drag_finish"); }
void gtk_drag_get_data(void) { _stub_abort("gtk_drag_get_data"); }
void gtk_drag_get_source_widget(void) { _stub_abort("gtk_drag_get_source_widget"); }
void gtk_drag_set_icon_pixbuf(void) { _stub_abort("gtk_drag_set_icon_pixbuf"); }
void gtk_drag_set_icon_surface(void) { _stub_abort("gtk_drag_set_icon_surface"); }
void gtk_drag_set_icon_widget(void) { _stub_abort("gtk_drag_set_icon_widget"); }
void gtk_editable_get_type(void) { _stub_abort("gtk_editable_get_type"); }
void gtk_editable_select_region(void) { _stub_abort("gtk_editable_select_region"); }
void gtk_entry_get_text(void) { _stub_abort("gtk_entry_get_text"); }
void gtk_entry_get_type(void) { _stub_abort("gtk_entry_get_type"); }
void gtk_entry_new(void) { _stub_abort("gtk_entry_new"); }
void gtk_entry_set_activates_default(void) { _stub_abort("gtk_entry_set_activates_default"); }
void gtk_entry_set_text(void) { _stub_abort("gtk_entry_set_text"); }
void gtk_enumerate_printers(void) { _stub_abort("gtk_enumerate_printers"); }
void gtk_file_chooser_add_filter(void) { _stub_abort("gtk_file_chooser_add_filter"); }
void gtk_file_chooser_dialog_new(void) { _stub_abort("gtk_file_chooser_dialog_new"); }
void gtk_file_chooser_get_filenames(void) { _stub_abort("gtk_file_chooser_get_filenames"); }
void gtk_file_chooser_get_filter(void) { _stub_abort("gtk_file_chooser_get_filter"); }
void gtk_file_chooser_get_preview_filename(void) { _stub_abort("gtk_file_chooser_get_preview_filename"); }
void gtk_file_chooser_get_type(void) { _stub_abort("gtk_file_chooser_get_type"); }
void gtk_file_chooser_get_uri(void) { _stub_abort("gtk_file_chooser_get_uri"); }
void gtk_file_chooser_list_filters(void) { _stub_abort("gtk_file_chooser_list_filters"); }
void gtk_file_chooser_set_current_folder(void) { _stub_abort("gtk_file_chooser_set_current_folder"); }
void gtk_file_chooser_set_current_name(void) { _stub_abort("gtk_file_chooser_set_current_name"); }
void gtk_file_chooser_set_do_overwrite_confirmation(void) { _stub_abort("gtk_file_chooser_set_do_overwrite_confirmation"); }
void gtk_file_chooser_set_filename(void) { _stub_abort("gtk_file_chooser_set_filename"); }
void gtk_file_chooser_set_filter(void) { _stub_abort("gtk_file_chooser_set_filter"); }
void gtk_file_chooser_set_local_only(void) { _stub_abort("gtk_file_chooser_set_local_only"); }
void gtk_file_chooser_set_preview_widget_active(void) { _stub_abort("gtk_file_chooser_set_preview_widget_active"); }
void gtk_file_chooser_set_preview_widget(void) { _stub_abort("gtk_file_chooser_set_preview_widget"); }
void gtk_file_chooser_set_select_multiple(void) { _stub_abort("gtk_file_chooser_set_select_multiple"); }
void gtk_file_chooser_widget_get_type(void) { _stub_abort("gtk_file_chooser_widget_get_type"); }
void gtk_file_filter_add_pattern(void) { _stub_abort("gtk_file_filter_add_pattern"); }
void gtk_file_filter_new(void) { _stub_abort("gtk_file_filter_new"); }
void gtk_file_filter_set_name(void) { _stub_abort("gtk_file_filter_set_name"); }
void gtk_fixed_new(void) { _stub_abort("gtk_fixed_new"); }
void gtk_frame_new(void) { _stub_abort("gtk_frame_new"); }
void gtk_get_current_event_time(void) { _stub_abort("gtk_get_current_event_time"); }
void gtk_get_major_version(void) { _stub_abort("gtk_get_major_version"); }
void gtk_get_micro_version(void) { _stub_abort("gtk_get_micro_version"); }
void gtk_get_minor_version(void) { _stub_abort("gtk_get_minor_version"); }
void gtk_grab_add(void) { _stub_abort("gtk_grab_add"); }
void gtk_grab_remove(void) { _stub_abort("gtk_grab_remove"); }
void gtk_grid_attach(void) { _stub_abort("gtk_grid_attach"); }
void gtk_grid_get_type(void) { _stub_abort("gtk_grid_get_type"); }
void gtk_grid_new(void) { _stub_abort("gtk_grid_new"); }
void gtk_grid_set_column_spacing(void) { _stub_abort("gtk_grid_set_column_spacing"); }
void gtk_grid_set_row_spacing(void) { _stub_abort("gtk_grid_set_row_spacing"); }
void gtk_header_bar_new(void) { _stub_abort("gtk_header_bar_new"); }
void gtk_icon_info_load_symbolic(void) { _stub_abort("gtk_icon_info_load_symbolic"); }
void gtk_icon_theme_get_default(void) { _stub_abort("gtk_icon_theme_get_default"); }
void gtk_icon_theme_get_icon_sizes(void) { _stub_abort("gtk_icon_theme_get_icon_sizes"); }
void gtk_icon_theme_lookup_by_gicon_for_scale(void) { _stub_abort("gtk_icon_theme_lookup_by_gicon_for_scale"); }
void gtk_icon_theme_lookup_icon_for_scale(void) { _stub_abort("gtk_icon_theme_lookup_icon_for_scale"); }
void gtk_image_get_type(void) { _stub_abort("gtk_image_get_type"); }
void gtk_image_new_from_icon_name(void) { _stub_abort("gtk_image_new_from_icon_name"); }
void gtk_image_new(void) { _stub_abort("gtk_image_new"); }
void gtk_image_set_from_pixbuf(void) { _stub_abort("gtk_image_set_from_pixbuf"); }
void gtk_im_context_filter_keypress(void) { _stub_abort("gtk_im_context_filter_keypress"); }
void gtk_im_context_focus_in(void) { _stub_abort("gtk_im_context_focus_in"); }
void gtk_im_context_focus_out(void) { _stub_abort("gtk_im_context_focus_out"); }
void gtk_im_context_get_preedit_string(void) { _stub_abort("gtk_im_context_get_preedit_string"); }
void gtk_im_context_reset(void) { _stub_abort("gtk_im_context_reset"); }
void gtk_im_context_set_client_window(void) { _stub_abort("gtk_im_context_set_client_window"); }
void gtk_im_context_set_cursor_location(void) { _stub_abort("gtk_im_context_set_cursor_location"); }
void gtk_im_context_set_surrounding(void) { _stub_abort("gtk_im_context_set_surrounding"); }
void gtk_im_context_simple_new(void) { _stub_abort("gtk_im_context_simple_new"); }
void gtk_im_multicontext_get_context_id(void) { _stub_abort("gtk_im_multicontext_get_context_id"); }
void gtk_im_multicontext_get_type(void) { _stub_abort("gtk_im_multicontext_get_type"); }
void gtk_im_multicontext_new(void) { _stub_abort("gtk_im_multicontext_new"); }
void gtk_init_check(void) { _stub_abort("gtk_init_check"); }
void gtk_init(void) { _stub_abort("gtk_init"); }
void gtk_key_snooper_install(void) { _stub_abort("gtk_key_snooper_install"); }
void gtk_key_snooper_remove(void) { _stub_abort("gtk_key_snooper_remove"); }
void gtk_label_get_type(void) { _stub_abort("gtk_label_get_type"); }
void gtk_label_new(void) { _stub_abort("gtk_label_new"); }
void gtk_label_set_markup(void) { _stub_abort("gtk_label_set_markup"); }
void gtk_link_button_new(void) { _stub_abort("gtk_link_button_new"); }
void gtk_main_do_event(void) { _stub_abort("gtk_main_do_event"); }
void gtk_main_iteration(void) { _stub_abort("gtk_main_iteration"); }
void gtk_menu_attach_to_widget(void) { _stub_abort("gtk_menu_attach_to_widget"); }
void gtk_menu_bar_new(void) { _stub_abort("gtk_menu_bar_new"); }
void gtk_menu_get_type(void) { _stub_abort("gtk_menu_get_type"); }
void gtk_menu_item_new(void) { _stub_abort("gtk_menu_item_new"); }
void gtk_menu_new_from_model(void) { _stub_abort("gtk_menu_new_from_model"); }
void gtk_menu_new(void) { _stub_abort("gtk_menu_new"); }
void gtk_menu_popdown(void) { _stub_abort("gtk_menu_popdown"); }
void gtk_menu_shell_append(void) { _stub_abort("gtk_menu_shell_append"); }
void gtk_menu_shell_get_type(void) { _stub_abort("gtk_menu_shell_get_type"); }
void gtk_message_dialog_new(void) { _stub_abort("gtk_message_dialog_new"); }
void gtk_offscreen_window_new(void) { _stub_abort("gtk_offscreen_window_new"); }
void gtk_page_setup_copy(void) { _stub_abort("gtk_page_setup_copy"); }
void gtk_page_setup_get_bottom_margin(void) { _stub_abort("gtk_page_setup_get_bottom_margin"); }
void gtk_page_setup_get_left_margin(void) { _stub_abort("gtk_page_setup_get_left_margin"); }
void gtk_page_setup_get_orientation(void) { _stub_abort("gtk_page_setup_get_orientation"); }
void gtk_page_setup_get_paper_size(void) { _stub_abort("gtk_page_setup_get_paper_size"); }
void gtk_page_setup_get_right_margin(void) { _stub_abort("gtk_page_setup_get_right_margin"); }
void gtk_page_setup_get_top_margin(void) { _stub_abort("gtk_page_setup_get_top_margin"); }
void gtk_page_setup_new(void) { _stub_abort("gtk_page_setup_new"); }
void gtk_page_setup_set_bottom_margin(void) { _stub_abort("gtk_page_setup_set_bottom_margin"); }
void gtk_page_setup_set_left_margin(void) { _stub_abort("gtk_page_setup_set_left_margin"); }
void gtk_page_setup_set_orientation(void) { _stub_abort("gtk_page_setup_set_orientation"); }
void gtk_page_setup_set_paper_size_and_default_margins(void) { _stub_abort("gtk_page_setup_set_paper_size_and_default_margins"); }
void gtk_page_setup_set_paper_size(void) { _stub_abort("gtk_page_setup_set_paper_size"); }
void gtk_page_setup_set_right_margin(void) { _stub_abort("gtk_page_setup_set_right_margin"); }
void gtk_page_setup_set_top_margin(void) { _stub_abort("gtk_page_setup_set_top_margin"); }
void gtk_page_setup_to_key_file(void) { _stub_abort("gtk_page_setup_to_key_file"); }
void gtk_paper_size_free(void) { _stub_abort("gtk_paper_size_free"); }
void gtk_paper_size_get_display_name(void) { _stub_abort("gtk_paper_size_get_display_name"); }
void gtk_paper_size_get_height(void) { _stub_abort("gtk_paper_size_get_height"); }
void gtk_paper_size_get_name(void) { _stub_abort("gtk_paper_size_get_name"); }
void gtk_paper_size_get_width(void) { _stub_abort("gtk_paper_size_get_width"); }
void gtk_paper_size_is_custom(void) { _stub_abort("gtk_paper_size_is_custom"); }
void gtk_paper_size_is_equal(void) { _stub_abort("gtk_paper_size_is_equal"); }
void gtk_paper_size_new_custom(void) { _stub_abort("gtk_paper_size_new_custom"); }
void gtk_paper_size_new(void) { _stub_abort("gtk_paper_size_new"); }
void gtk_paper_size_set_size(void) { _stub_abort("gtk_paper_size_set_size"); }
void gtk_parse_args(void) { _stub_abort("gtk_parse_args"); }
void gtk_printer_get_name(void) { _stub_abort("gtk_printer_get_name"); }
void gtk_printer_get_type(void) { _stub_abort("gtk_printer_get_type"); }
void gtk_print_job_new(void) { _stub_abort("gtk_print_job_new"); }
void gtk_print_job_send(void) { _stub_abort("gtk_print_job_send"); }
void gtk_print_job_set_source_file(void) { _stub_abort("gtk_print_job_set_source_file"); }
void gtk_print_run_page_setup_dialog(void) { _stub_abort("gtk_print_run_page_setup_dialog"); }
void gtk_print_settings_copy(void) { _stub_abort("gtk_print_settings_copy"); }
void gtk_print_settings_foreach(void) { _stub_abort("gtk_print_settings_foreach"); }
void gtk_print_settings_get_duplex(void) { _stub_abort("gtk_print_settings_get_duplex"); }
void gtk_print_settings_get(void) { _stub_abort("gtk_print_settings_get"); }
void gtk_print_settings_get_n_copies(void) { _stub_abort("gtk_print_settings_get_n_copies"); }
void gtk_print_settings_get_page_ranges(void) { _stub_abort("gtk_print_settings_get_page_ranges"); }
void gtk_print_settings_get_paper_size(void) { _stub_abort("gtk_print_settings_get_paper_size"); }
void gtk_print_settings_get_printer(void) { _stub_abort("gtk_print_settings_get_printer"); }
void gtk_print_settings_get_print_pages(void) { _stub_abort("gtk_print_settings_get_print_pages"); }
void gtk_print_settings_get_resolution(void) { _stub_abort("gtk_print_settings_get_resolution"); }
void gtk_print_settings_get_reverse(void) { _stub_abort("gtk_print_settings_get_reverse"); }
void gtk_print_settings_get_scale(void) { _stub_abort("gtk_print_settings_get_scale"); }
void gtk_print_settings_get_use_color(void) { _stub_abort("gtk_print_settings_get_use_color"); }
void gtk_print_settings_has_key(void) { _stub_abort("gtk_print_settings_has_key"); }
void gtk_print_settings_new(void) { _stub_abort("gtk_print_settings_new"); }
void gtk_print_settings_set_duplex(void) { _stub_abort("gtk_print_settings_set_duplex"); }
void gtk_print_settings_set(void) { _stub_abort("gtk_print_settings_set"); }
void gtk_print_settings_set_n_copies(void) { _stub_abort("gtk_print_settings_set_n_copies"); }
void gtk_print_settings_set_number_up(void) { _stub_abort("gtk_print_settings_set_number_up"); }
void gtk_print_settings_set_orientation(void) { _stub_abort("gtk_print_settings_set_orientation"); }
void gtk_print_settings_set_page_ranges(void) { _stub_abort("gtk_print_settings_set_page_ranges"); }
void gtk_print_settings_set_paper_size(void) { _stub_abort("gtk_print_settings_set_paper_size"); }
void gtk_print_settings_set_printer(void) { _stub_abort("gtk_print_settings_set_printer"); }
void gtk_print_settings_set_print_pages(void) { _stub_abort("gtk_print_settings_set_print_pages"); }
void gtk_print_settings_set_resolution(void) { _stub_abort("gtk_print_settings_set_resolution"); }
void gtk_print_settings_set_reverse(void) { _stub_abort("gtk_print_settings_set_reverse"); }
void gtk_print_settings_set_scale(void) { _stub_abort("gtk_print_settings_set_scale"); }
void gtk_print_settings_set_use_color(void) { _stub_abort("gtk_print_settings_set_use_color"); }
void gtk_print_unix_dialog_add_custom_tab(void) { _stub_abort("gtk_print_unix_dialog_add_custom_tab"); }
void gtk_print_unix_dialog_get_page_setup(void) { _stub_abort("gtk_print_unix_dialog_get_page_setup"); }
void gtk_print_unix_dialog_get_selected_printer(void) { _stub_abort("gtk_print_unix_dialog_get_selected_printer"); }
void gtk_print_unix_dialog_get_settings(void) { _stub_abort("gtk_print_unix_dialog_get_settings"); }
void gtk_print_unix_dialog_get_type(void) { _stub_abort("gtk_print_unix_dialog_get_type"); }
void gtk_print_unix_dialog_new(void) { _stub_abort("gtk_print_unix_dialog_new"); }
void gtk_print_unix_dialog_set_manual_capabilities(void) { _stub_abort("gtk_print_unix_dialog_set_manual_capabilities"); }
void gtk_print_unix_dialog_set_page_setup(void) { _stub_abort("gtk_print_unix_dialog_set_page_setup"); }
void gtk_print_unix_dialog_set_settings(void) { _stub_abort("gtk_print_unix_dialog_set_settings"); }
void gtk_propagate_event(void) { _stub_abort("gtk_propagate_event"); }
void gtk_recent_manager_add_item(void) { _stub_abort("gtk_recent_manager_add_item"); }
void gtk_recent_manager_get_default(void) { _stub_abort("gtk_recent_manager_get_default"); }
void gtk_render_background(void) { _stub_abort("gtk_render_background"); }
void gtk_render_frame(void) { _stub_abort("gtk_render_frame"); }
void gtk_scrollbar_new(void) { _stub_abort("gtk_scrollbar_new"); }
void gtk_scrolled_window_new(void) { _stub_abort("gtk_scrolled_window_new"); }
void gtk_selection_data_get_data(void) { _stub_abort("gtk_selection_data_get_data"); }
void gtk_selection_data_get_length(void) { _stub_abort("gtk_selection_data_get_length"); }
void gtk_selection_data_get_selection(void) { _stub_abort("gtk_selection_data_get_selection"); }
void gtk_selection_data_get_target(void) { _stub_abort("gtk_selection_data_get_target"); }
void gtk_selection_data_get_targets(void) { _stub_abort("gtk_selection_data_get_targets"); }
void gtk_selection_data_get_text(void) { _stub_abort("gtk_selection_data_get_text"); }
void gtk_selection_data_get_uris(void) { _stub_abort("gtk_selection_data_get_uris"); }
void gtk_selection_data_set(void) { _stub_abort("gtk_selection_data_set"); }
void gtk_selection_data_set_pixbuf(void) { _stub_abort("gtk_selection_data_set_pixbuf"); }
void gtk_selection_data_set_text(void) { _stub_abort("gtk_selection_data_set_text"); }
void gtk_settings_get_default(void) { _stub_abort("gtk_settings_get_default"); }
void gtk_show_uri(void) { _stub_abort("gtk_show_uri"); }
void gtk_style_context_add_class(void) { _stub_abort("gtk_style_context_add_class"); }
void gtk_style_context_add_provider_for_screen(void) { _stub_abort("gtk_style_context_add_provider_for_screen"); }
void gtk_style_context_add_provider(void) { _stub_abort("gtk_style_context_add_provider"); }
void gtk_style_context_get_background_color(void) { _stub_abort("gtk_style_context_get_background_color"); }
void gtk_style_context_get_border_color(void) { _stub_abort("gtk_style_context_get_border_color"); }
void gtk_style_context_get_border(void) { _stub_abort("gtk_style_context_get_border"); }
void gtk_style_context_get_color(void) { _stub_abort("gtk_style_context_get_color"); }
void gtk_style_context_get(void) { _stub_abort("gtk_style_context_get"); }
void gtk_style_context_get_path(void) { _stub_abort("gtk_style_context_get_path"); }
void gtk_style_context_get_property(void) { _stub_abort("gtk_style_context_get_property"); }
void gtk_style_context_get_state(void) { _stub_abort("gtk_style_context_get_state"); }
void gtk_style_context_list_classes(void) { _stub_abort("gtk_style_context_list_classes"); }
void gtk_style_context_lookup_color(void) { _stub_abort("gtk_style_context_lookup_color"); }
void gtk_style_context_new(void) { _stub_abort("gtk_style_context_new"); }
void gtk_style_context_remove_provider_for_screen(void) { _stub_abort("gtk_style_context_remove_provider_for_screen"); }
void gtk_style_context_set_parent(void) { _stub_abort("gtk_style_context_set_parent"); }
void gtk_style_context_set_path(void) { _stub_abort("gtk_style_context_set_path"); }
void gtk_style_context_set_state(void) { _stub_abort("gtk_style_context_set_state"); }
void gtk_style_provider_get_type(void) { _stub_abort("gtk_style_provider_get_type"); }
void gtk_target_list_add(void) { _stub_abort("gtk_target_list_add"); }
void gtk_target_list_add_image_targets(void) { _stub_abort("gtk_target_list_add_image_targets"); }
void gtk_target_list_add_text_targets(void) { _stub_abort("gtk_target_list_add_text_targets"); }
void gtk_target_list_new(void) { _stub_abort("gtk_target_list_new"); }
void gtk_target_list_unref(void) { _stub_abort("gtk_target_list_unref"); }
void gtk_targets_include_image(void) { _stub_abort("gtk_targets_include_image"); }
void gtk_targets_include_text(void) { _stub_abort("gtk_targets_include_text"); }
void gtk_target_table_free(void) { _stub_abort("gtk_target_table_free"); }
void gtk_target_table_new_from_list(void) { _stub_abort("gtk_target_table_new_from_list"); }
void gtk_text_view_new(void) { _stub_abort("gtk_text_view_new"); }
void gtk_toggle_button_get_active(void) { _stub_abort("gtk_toggle_button_get_active"); }
void gtk_toggle_button_get_type(void) { _stub_abort("gtk_toggle_button_get_type"); }
void gtk_toggle_button_set_active(void) { _stub_abort("gtk_toggle_button_set_active"); }
void gtk_tooltip_get_type(void) { _stub_abort("gtk_tooltip_get_type"); }
void gtk_tree_view_append_column(void) { _stub_abort("gtk_tree_view_append_column"); }
void gtk_tree_view_column_get_button(void) { _stub_abort("gtk_tree_view_column_get_button"); }
void gtk_tree_view_column_new(void) { _stub_abort("gtk_tree_view_column_new"); }
void gtk_tree_view_column_set_title(void) { _stub_abort("gtk_tree_view_column_set_title"); }
void gtk_tree_view_get_type(void) { _stub_abort("gtk_tree_view_get_type"); }
void gtk_tree_view_new(void) { _stub_abort("gtk_tree_view_new"); }
void gtk_widget_add_events(void) { _stub_abort("gtk_widget_add_events"); }
void gtk_widget_class_find_style_property(void) { _stub_abort("gtk_widget_class_find_style_property"); }
void gtk_widget_destroy(void) { _stub_abort("gtk_widget_destroy"); }
void gtk_widget_event(void) { _stub_abort("gtk_widget_event"); }
void gtk_widget_get_accessible(void) { _stub_abort("gtk_widget_get_accessible"); }
void gtk_widget_get_allocation(void) { _stub_abort("gtk_widget_get_allocation"); }
void gtk_widget_get_display(void) { _stub_abort("gtk_widget_get_display"); }
void gtk_widget_get_events(void) { _stub_abort("gtk_widget_get_events"); }
void gtk_widget_get_has_window(void) { _stub_abort("gtk_widget_get_has_window"); }
void gtk_widget_get_mapped(void) { _stub_abort("gtk_widget_get_mapped"); }
void gtk_widget_get_parent(void) { _stub_abort("gtk_widget_get_parent"); }
void gtk_widget_get_parent_window(void) { _stub_abort("gtk_widget_get_parent_window"); }
void gtk_widget_get_preferred_height(void) { _stub_abort("gtk_widget_get_preferred_height"); }
void gtk_widget_get_preferred_width(void) { _stub_abort("gtk_widget_get_preferred_width"); }
void gtk_widget_get_realized(void) { _stub_abort("gtk_widget_get_realized"); }
void gtk_widget_get_screen(void) { _stub_abort("gtk_widget_get_screen"); }
void gtk_widget_get_state_flags(void) { _stub_abort("gtk_widget_get_state_flags"); }
void gtk_widget_get_style_context(void) { _stub_abort("gtk_widget_get_style_context"); }
void gtk_widget_get_toplevel(void) { _stub_abort("gtk_widget_get_toplevel"); }
void gtk_widget_get_type(void) { _stub_abort("gtk_widget_get_type"); }
void gtk_widget_get_visible(void) { _stub_abort("gtk_widget_get_visible"); }
void gtk_widget_get_visual(void) { _stub_abort("gtk_widget_get_visual"); }
void gtk_widget_get_window(void) { _stub_abort("gtk_widget_get_window"); }
void gtk_widget_grab_focus(void) { _stub_abort("gtk_widget_grab_focus"); }
void gtk_widget_has_focus(void) { _stub_abort("gtk_widget_has_focus"); }
void gtk_widget_has_grab(void) { _stub_abort("gtk_widget_has_grab"); }
void gtk_widget_hide(void) { _stub_abort("gtk_widget_hide"); }
void gtk_widget_insert_action_group(void) { _stub_abort("gtk_widget_insert_action_group"); }
void gtk_widget_is_focus(void) { _stub_abort("gtk_widget_is_focus"); }
void gtk_widget_is_visible(void) { _stub_abort("gtk_widget_is_visible"); }
void gtk_widget_override_background_color(void) { _stub_abort("gtk_widget_override_background_color"); }
void gtk_widget_path_append_type(void) { _stub_abort("gtk_widget_path_append_type"); }
void gtk_widget_path_copy(void) { _stub_abort("gtk_widget_path_copy"); }
void gtk_widget_path_get_object_type(void) { _stub_abort("gtk_widget_path_get_object_type"); }
void gtk_widget_path_iter_add_class(void) { _stub_abort("gtk_widget_path_iter_add_class"); }
void gtk_widget_path_new(void) { _stub_abort("gtk_widget_path_new"); }
void gtk_widget_path_unref(void) { _stub_abort("gtk_widget_path_unref"); }
void gtk_widget_realize(void) { _stub_abort("gtk_widget_realize"); }
void gtk_widget_register_window(void) { _stub_abort("gtk_widget_register_window"); }
void gtk_widget_reparent(void) { _stub_abort("gtk_widget_reparent"); }
void gtk_widget_set_allocation(void) { _stub_abort("gtk_widget_set_allocation"); }
void gtk_widget_set_app_paintable(void) { _stub_abort("gtk_widget_set_app_paintable"); }
void gtk_widget_set_can_focus(void) { _stub_abort("gtk_widget_set_can_focus"); }
void gtk_widget_set_double_buffered(void) { _stub_abort("gtk_widget_set_double_buffered"); }
void gtk_widget_set_has_window(void) { _stub_abort("gtk_widget_set_has_window"); }
void gtk_widget_set_mapped(void) { _stub_abort("gtk_widget_set_mapped"); }
void gtk_widget_set_name(void) { _stub_abort("gtk_widget_set_name"); }
void gtk_widget_set_opacity(void) { _stub_abort("gtk_widget_set_opacity"); }
void gtk_widget_set_realized(void) { _stub_abort("gtk_widget_set_realized"); }
void gtk_widget_set_redraw_on_allocate(void) { _stub_abort("gtk_widget_set_redraw_on_allocate"); }
void gtk_widget_set_sensitive(void) { _stub_abort("gtk_widget_set_sensitive"); }
void gtk_widget_set_size_request(void) { _stub_abort("gtk_widget_set_size_request"); }
void gtk_widget_set_visual(void) { _stub_abort("gtk_widget_set_visual"); }
void gtk_widget_set_window(void) { _stub_abort("gtk_widget_set_window"); }
void gtk_widget_show_all(void) { _stub_abort("gtk_widget_show_all"); }
void gtk_widget_show(void) { _stub_abort("gtk_widget_show"); }
void gtk_widget_size_allocate(void) { _stub_abort("gtk_widget_size_allocate"); }
void gtk_widget_style_get(void) { _stub_abort("gtk_widget_style_get"); }
void gtk_widget_unmap(void) { _stub_abort("gtk_widget_unmap"); }
void gtk_widget_unrealize(void) { _stub_abort("gtk_widget_unrealize"); }
void gtk_widget_unregister_window(void) { _stub_abort("gtk_widget_unregister_window"); }
void gtk_window_close(void) { _stub_abort("gtk_window_close"); }
void gtk_window_deiconify(void) { _stub_abort("gtk_window_deiconify"); }
void gtk_window_fullscreen(void) { _stub_abort("gtk_window_fullscreen"); }
void gtk_window_get_group(void) { _stub_abort("gtk_window_get_group"); }
void gtk_window_get_modal(void) { _stub_abort("gtk_window_get_modal"); }
void gtk_window_get_position(void) { _stub_abort("gtk_window_get_position"); }
void gtk_window_get_size(void) { _stub_abort("gtk_window_get_size"); }
void gtk_window_get_title(void) { _stub_abort("gtk_window_get_title"); }
void gtk_window_get_transient_for(void) { _stub_abort("gtk_window_get_transient_for"); }
void gtk_window_get_type(void) { _stub_abort("gtk_window_get_type"); }
void gtk_window_get_type_hint(void) { _stub_abort("gtk_window_get_type_hint"); }
void gtk_window_group_add_window(void) { _stub_abort("gtk_window_group_add_window"); }
void gtk_window_group_get_current_grab(void) { _stub_abort("gtk_window_group_get_current_grab"); }
void gtk_window_group_new(void) { _stub_abort("gtk_window_group_new"); }
void gtk_window_iconify(void) { _stub_abort("gtk_window_iconify"); }
void gtk_window_is_active(void) { _stub_abort("gtk_window_is_active"); }
void gtk_window_maximize(void) { _stub_abort("gtk_window_maximize"); }
void gtk_window_move(void) { _stub_abort("gtk_window_move"); }
void gtk_window_new(void) { _stub_abort("gtk_window_new"); }
void gtk_window_present(void) { _stub_abort("gtk_window_present"); }
void gtk_window_present_with_time(void) { _stub_abort("gtk_window_present_with_time"); }
void gtk_window_resize(void) { _stub_abort("gtk_window_resize"); }
void gtk_window_set_decorated(void) { _stub_abort("gtk_window_set_decorated"); }
void gtk_window_set_destroy_with_parent(void) { _stub_abort("gtk_window_set_destroy_with_parent"); }
void gtk_window_set_focus_on_map(void) { _stub_abort("gtk_window_set_focus_on_map"); }
void gtk_window_set_geometry_hints(void) { _stub_abort("gtk_window_set_geometry_hints"); }
void gtk_window_set_icon(void) { _stub_abort("gtk_window_set_icon"); }
void gtk_window_set_icon_name(void) { _stub_abort("gtk_window_set_icon_name"); }
void gtk_window_set_keep_above(void) { _stub_abort("gtk_window_set_keep_above"); }
void gtk_window_set_modal(void) { _stub_abort("gtk_window_set_modal"); }
void gtk_window_set_screen(void) { _stub_abort("gtk_window_set_screen"); }
void gtk_window_set_skip_taskbar_hint(void) { _stub_abort("gtk_window_set_skip_taskbar_hint"); }
void gtk_window_set_startup_id(void) { _stub_abort("gtk_window_set_startup_id"); }
void gtk_window_set_titlebar(void) { _stub_abort("gtk_window_set_titlebar"); }
void gtk_window_set_title(void) { _stub_abort("gtk_window_set_title"); }
void gtk_window_set_transient_for(void) { _stub_abort("gtk_window_set_transient_for"); }
void gtk_window_set_type_hint(void) { _stub_abort("gtk_window_set_type_hint"); }
void gtk_window_unfullscreen(void) { _stub_abort("gtk_window_unfullscreen"); }
void gtk_window_unmaximize(void) { _stub_abort("gtk_window_unmaximize"); }
