/* Auto-generated stub. All functions abort if called. */
#include <stdlib.h>
#include <stdio.h>

static void __attribute__((noreturn)) _stub_abort(const char *sym) {
    fprintf(stderr, "FATAL: stub called: %s\n", sym);
    abort();
}

void g_action_get_type(void) { _stub_abort("g_action_get_type"); }
void g_action_group_get_type(void) { _stub_abort("g_action_group_get_type"); }
void g_action_map_add_action(void) { _stub_abort("g_action_map_add_action"); }
void g_action_map_get_type(void) { _stub_abort("g_action_map_get_type"); }
void g_action_map_remove_action(void) { _stub_abort("g_action_map_remove_action"); }
void g_app_info_create_from_commandline(void) { _stub_abort("g_app_info_create_from_commandline"); }
void g_app_info_get_all_for_type(void) { _stub_abort("g_app_info_get_all_for_type"); }
void g_app_info_get_all(void) { _stub_abort("g_app_info_get_all"); }
void g_app_info_get_commandline(void) { _stub_abort("g_app_info_get_commandline"); }
void g_app_info_get_default_for_type(void) { _stub_abort("g_app_info_get_default_for_type"); }
void g_app_info_get_default_for_uri_scheme(void) { _stub_abort("g_app_info_get_default_for_uri_scheme"); }
void g_app_info_get_executable(void) { _stub_abort("g_app_info_get_executable"); }
void g_app_info_get_icon(void) { _stub_abort("g_app_info_get_icon"); }
void g_app_info_get_id(void) { _stub_abort("g_app_info_get_id"); }
void g_app_info_get_name(void) { _stub_abort("g_app_info_get_name"); }
void g_app_info_get_type(void) { _stub_abort("g_app_info_get_type"); }
void g_app_info_launch_default_for_uri(void) { _stub_abort("g_app_info_launch_default_for_uri"); }
void g_app_info_launch(void) { _stub_abort("g_app_info_launch"); }
void g_app_info_launch_uris(void) { _stub_abort("g_app_info_launch_uris"); }
void g_app_info_set_as_default_for_extension(void) { _stub_abort("g_app_info_set_as_default_for_extension"); }
void g_app_info_set_as_default_for_type(void) { _stub_abort("g_app_info_set_as_default_for_type"); }
void g_app_info_set_as_last_used_for_type(void) { _stub_abort("g_app_info_set_as_last_used_for_type"); }
void g_app_info_supports_uris(void) { _stub_abort("g_app_info_supports_uris"); }
void g_app_launch_context_get_startup_notify_id(void) { _stub_abort("g_app_launch_context_get_startup_notify_id"); }
void g_app_launch_context_get_type(void) { _stub_abort("g_app_launch_context_get_type"); }
void g_app_launch_context_setenv(void) { _stub_abort("g_app_launch_context_setenv"); }
void g_app_launch_context_unsetenv(void) { _stub_abort("g_app_launch_context_unsetenv"); }
void g_bus_get_finish(void) { _stub_abort("g_bus_get_finish"); }
void g_bus_get(void) { _stub_abort("g_bus_get"); }
void g_bus_own_name(void) { _stub_abort("g_bus_own_name"); }
void g_bus_own_name_on_connection(void) { _stub_abort("g_bus_own_name_on_connection"); }
void g_bus_unown_name(void) { _stub_abort("g_bus_unown_name"); }
void g_bus_unwatch_name(void) { _stub_abort("g_bus_unwatch_name"); }
void g_bus_watch_name(void) { _stub_abort("g_bus_watch_name"); }
void g_cancellable_cancel(void) { _stub_abort("g_cancellable_cancel"); }
void g_cancellable_new(void) { _stub_abort("g_cancellable_new"); }
void g_content_type_from_mime_type(void) { _stub_abort("g_content_type_from_mime_type"); }
void g_content_type_get_description(void) { _stub_abort("g_content_type_get_description"); }
void g_content_type_get_icon(void) { _stub_abort("g_content_type_get_icon"); }
void g_content_type_get_mime_type(void) { _stub_abort("g_content_type_get_mime_type"); }
void g_content_type_guess(void) { _stub_abort("g_content_type_guess"); }
void g_content_type_is_unknown(void) { _stub_abort("g_content_type_is_unknown"); }
void g_dbus_connection_emit_signal(void) { _stub_abort("g_dbus_connection_emit_signal"); }
void g_dbus_connection_get_unique_name(void) { _stub_abort("g_dbus_connection_get_unique_name"); }
void g_dbus_connection_register_object(void) { _stub_abort("g_dbus_connection_register_object"); }
void g_dbus_connection_send_message(void) { _stub_abort("g_dbus_connection_send_message"); }
void g_dbus_connection_signal_subscribe(void) { _stub_abort("g_dbus_connection_signal_subscribe"); }
void g_dbus_connection_signal_unsubscribe(void) { _stub_abort("g_dbus_connection_signal_unsubscribe"); }
void g_dbus_connection_unregister_object(void) { _stub_abort("g_dbus_connection_unregister_object"); }
void g_dbus_error_quark(void) { _stub_abort("g_dbus_error_quark"); }
void g_dbus_message_new_method_call(void) { _stub_abort("g_dbus_message_new_method_call"); }
void g_dbus_method_invocation_return_error(void) { _stub_abort("g_dbus_method_invocation_return_error"); }
void g_dbus_method_invocation_return_value(void) { _stub_abort("g_dbus_method_invocation_return_value"); }
void g_dbus_node_info_new_for_xml(void) { _stub_abort("g_dbus_node_info_new_for_xml"); }
void g_dbus_node_info_unref(void) { _stub_abort("g_dbus_node_info_unref"); }
void g_dbus_proxy_call_finish(void) { _stub_abort("g_dbus_proxy_call_finish"); }
void g_dbus_proxy_call(void) { _stub_abort("g_dbus_proxy_call"); }
void g_dbus_proxy_call_sync(void) { _stub_abort("g_dbus_proxy_call_sync"); }
void g_dbus_proxy_call_with_unix_fd_list_finish(void) { _stub_abort("g_dbus_proxy_call_with_unix_fd_list_finish"); }
void g_dbus_proxy_call_with_unix_fd_list(void) { _stub_abort("g_dbus_proxy_call_with_unix_fd_list"); }
void g_dbus_proxy_get_cached_property(void) { _stub_abort("g_dbus_proxy_get_cached_property"); }
void g_dbus_proxy_get_connection(void) { _stub_abort("g_dbus_proxy_get_connection"); }
void g_dbus_proxy_get_interface_name(void) { _stub_abort("g_dbus_proxy_get_interface_name"); }
void g_dbus_proxy_get_name(void) { _stub_abort("g_dbus_proxy_get_name"); }
void g_dbus_proxy_get_name_owner(void) { _stub_abort("g_dbus_proxy_get_name_owner"); }
void g_dbus_proxy_get_object_path(void) { _stub_abort("g_dbus_proxy_get_object_path"); }
void g_dbus_proxy_get_type(void) { _stub_abort("g_dbus_proxy_get_type"); }
void g_dbus_proxy_new_finish(void) { _stub_abort("g_dbus_proxy_new_finish"); }
void g_dbus_proxy_new_for_bus_finish(void) { _stub_abort("g_dbus_proxy_new_for_bus_finish"); }
void g_dbus_proxy_new_for_bus(void) { _stub_abort("g_dbus_proxy_new_for_bus"); }
void g_dbus_proxy_new_for_bus_sync(void) { _stub_abort("g_dbus_proxy_new_for_bus_sync"); }
void g_desktop_app_info_new(void) { _stub_abort("g_desktop_app_info_new"); }
void g_file_enumerate_children(void) { _stub_abort("g_file_enumerate_children"); }
void g_file_enumerator_next_file(void) { _stub_abort("g_file_enumerator_next_file"); }
void g_file_get_type(void) { _stub_abort("g_file_get_type"); }
void g_file_get_uri(void) { _stub_abort("g_file_get_uri"); }
void g_file_info_get_content_type(void) { _stub_abort("g_file_info_get_content_type"); }
void g_file_info_get_file_type(void) { _stub_abort("g_file_info_get_file_type"); }
void g_file_info_get_icon(void) { _stub_abort("g_file_info_get_icon"); }
void g_file_info_get_modification_time(void) { _stub_abort("g_file_info_get_modification_time"); }
void g_file_info_get_name(void) { _stub_abort("g_file_info_get_name"); }
void g_file_info_get_size(void) { _stub_abort("g_file_info_get_size"); }
void g_file_info_new(void) { _stub_abort("g_file_info_new"); }
void g_file_info_set_attribute_string(void) { _stub_abort("g_file_info_set_attribute_string"); }
void g_file_monitor_file(void) { _stub_abort("g_file_monitor_file"); }
void g_file_mount_enclosing_volume_finish(void) { _stub_abort("g_file_mount_enclosing_volume_finish"); }
void g_file_mount_enclosing_volume(void) { _stub_abort("g_file_mount_enclosing_volume"); }
void g_file_new_for_commandline_arg(void) { _stub_abort("g_file_new_for_commandline_arg"); }
void g_file_new_for_path(void) { _stub_abort("g_file_new_for_path"); }
void g_file_new_for_uri(void) { _stub_abort("g_file_new_for_uri"); }
void g_file_query_info(void) { _stub_abort("g_file_query_info"); }
void g_file_read(void) { _stub_abort("g_file_read"); }
void g_file_set_attributes_async(void) { _stub_abort("g_file_set_attributes_async"); }
void g_file_set_attributes_finish(void) { _stub_abort("g_file_set_attributes_finish"); }
void g_icon_to_string(void) { _stub_abort("g_icon_to_string"); }
void g_input_stream_get_type(void) { _stub_abort("g_input_stream_get_type"); }
void g_input_stream_read(void) { _stub_abort("g_input_stream_read"); }
void g_io_error_quark(void) { _stub_abort("g_io_error_quark"); }
void g_menu_append(void) { _stub_abort("g_menu_append"); }
void g_menu_append_item(void) { _stub_abort("g_menu_append_item"); }
void g_menu_append_section(void) { _stub_abort("g_menu_append_section"); }
void g_menu_item_new_submenu(void) { _stub_abort("g_menu_item_new_submenu"); }
void g_menu_item_set_attribute_value(void) { _stub_abort("g_menu_item_set_attribute_value"); }
void g_menu_model_get_type(void) { _stub_abort("g_menu_model_get_type"); }
void g_menu_new(void) { _stub_abort("g_menu_new"); }
void g_menu_remove_all(void) { _stub_abort("g_menu_remove_all"); }
void g_mount_operation_new(void) { _stub_abort("g_mount_operation_new"); }
void g_mount_operation_reply(void) { _stub_abort("g_mount_operation_reply"); }
void g_mount_operation_set_password(void) { _stub_abort("g_mount_operation_set_password"); }
void g_mount_operation_set_username(void) { _stub_abort("g_mount_operation_set_username"); }
void g_settings_get_value(void) { _stub_abort("g_settings_get_value"); }
void g_settings_list_keys(void) { _stub_abort("g_settings_list_keys"); }
void g_settings_list_schemas(void) { _stub_abort("g_settings_list_schemas"); }
void g_settings_new(void) { _stub_abort("g_settings_new"); }
void g_settings_set_string(void) { _stub_abort("g_settings_set_string"); }
void g_simple_action_group_new(void) { _stub_abort("g_simple_action_group_new"); }
void g_simple_action_new(void) { _stub_abort("g_simple_action_new"); }
void g_simple_action_new_stateful(void) { _stub_abort("g_simple_action_new_stateful"); }
void g_vfs_get_default(void) { _stub_abort("g_vfs_get_default"); }
void g_vfs_get_supported_uri_schemes(void) { _stub_abort("g_vfs_get_supported_uri_schemes"); }
