// Code generated by "stringer -type=ExitType"; DO NOT EDIT.

package kvm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExitUnknown-0]
	_ = x[ExitException-1]
	_ = x[ExitIO-2]
	_ = x[ExitHypercall-3]
	_ = x[ExitDebug-4]
	_ = x[ExitHlt-5]
	_ = x[ExitMMIO-6]
	_ = x[ExitIRQWindowOpen-7]
	_ = x[ExitShutdown-8]
	_ = x[ExitFailEntry-9]
	_ = x[ExitIntr-10]
	_ = x[ExitSetTPR-11]
	_ = x[ExitTPRAccess-12]
	_ = x[ExitDCR-15]
	_ = x[ExitNMI-16]
	_ = x[ExitInternalError-17]
}

const (
	_ExitType_name_0 = "ExitUnknownExitExceptionExitIOExitHypercallExitDebugExitHltExitMMIOExitIRQWindowOpenExitShutdownExitFailEntryExitIntrExitSetTPRExitTPRAccess"
	_ExitType_name_1 = "ExitDCRExitNMIExitInternalError"
)

var (
	_ExitType_index_0 = [...]uint8{0, 11, 24, 30, 43, 52, 59, 67, 84, 96, 109, 117, 127, 140}
	_ExitType_index_1 = [...]uint8{0, 7, 14, 31}
)

func (i ExitType) String() string {
	switch {
	case i <= 12:
		return _ExitType_name_0[_ExitType_index_0[i]:_ExitType_index_0[i+1]]
	case 15 <= i && i <= 17:
		i -= 15
		return _ExitType_name_1[_ExitType_index_1[i]:_ExitType_index_1[i+1]]
	default:
		return "ExitType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
